### ISSUE TITLE
Possible improvement for 'num2si' method

### ISSUE THREAD

**Issue by OshinoMoumou** [AleCandido/Lab3.2#1]
Greetings!
I noticed that in BobLightyear.py, 'num2si' method referred a StackOverflow post, while a [recent comment](https://stackoverflow.com/questions/17973278/python-decimal-engineering-notation-for-mili-10e-3-and-micro-10e-6#comment68611688_19270863) to it mentioned that _for x=0, we need a case so something like if x==0: exp=0, exp3=0_.
I'm trying to learn the usefulness of such small updates on StackOverflow. Would this comment help improve your code? I understand that such defect might not happen in real life situation. In that case, do you think this comment can help prevent future bugs (for example, when the code were reused somewhere else)?
I'll really appreciate it if you could kindly give me some feedback or suggestions. Thank you very much for your time.
Have a nice day!

**Comment by alecandido** [comment]
Being the exact same issue of https://github.com/AleCandido/Lab3/issues/1 you can read the reply there.
